apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
 
namespace: sample-blog

images:
- name: image-registry.openshift-image-registry.svc:5000/sample-blog/django 
  newName: image-registry.openshift-image-registry.svc:5000/sample-blog/django
  newTag: latest
- name: image-registry.openshift-image-registry.svc:5000/sample-blog/nginx
  newName: image-registry.openshift-image-registry.svc:5000/sample-blog/nginx
  newTag: latest

resources:
- django-deployment.yaml
- django-service.yaml
- mysql-service.yaml
- mysql-statefulset.yaml
- nginx-deployment.yaml
- nginx-route.yaml
- nginx-service.yaml
- redis-service.yaml
- redis-statefulset.yaml
