apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:  
    app: sample-blog
    app.kubernetes.io/part-of: sample-blog
spec:
  replicas: 1
  serviceName: mysql
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: docker.io/mysql:8.0.26
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_USER
          value: sampleblog
        - name: MYSQL_PASSWORD
          value: sampleblog
        - name: MYSQL_ROOT_PASSWORD
          value: sampleblog
        - name: MYSQL_DATABASE
          value: sampleblog
        imagePullPolicy: Always
