apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  labels:
    app: sample-blog
    app.kubernetes.io/part-of: sample-blog
spec:
  replicas: 1
  serviceName: redis
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: docker.io/redis:6.0.8
        volumeMounts:
        - mountPath: /data
          name: data
        ports:
        - containerPort: 6379
        imagePullPolicy: Always
      volumes:
      - name: data
        emptyDir: {}
